[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RSCG = "4e41d8b6-e438-5f9c-8b78-0c738ca8d379"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"
